### ISSUE TITLE
Which method to use to flash MIUI 22.1.19 ? 

### ISSUE THREAD

**Issue by ttcg52** [xjl12/android_device_xiaomi_atom#10]
I already downloaded the linked MIUI 22.1.19 ROM in https://github.com/xjl12/android_device_xiaomi_atom/releases/tag/1.4 but I was unable to flash it via MiFlash Tool (v2018.5.28.0). Is that the correct way to flash it? What may I be doing wrong?! Which is the correct way to flash it???!!! Please!!! Thanks!

**Comment by xjl12** [comment]
Just use a third-party recovery to flash it.
