### ISSUE TITLE
lineageos系统的功能

### ISSUE THREAD

**Issue by damieai** [xjl12/android_device_xiaomi_atom#14]
麻烦大佬加一个类DC调光在下一次构建的lineage OS中，希望可以拿来日用，可以的话测试一下类DC调光功能是否真的有效果，而不是无效果只是有个选项

**Comment by xjl12** [comment]
已添加https://github.com/xjl12/android_device_xiaomi_atom/commit/3757a6161033dee9ce836b350582ffc1ab7b596d

可在系统设置，显示，自定义显示设置里开启，有效
