### ISSUE TITLE
VoLTE正常吗

### ISSUE THREAD

**Issue by SaKongA** [xjl12/android_device_xiaomi_atom#3]
我看到这个树是从k30u哪里fork来的 k30u的VoLTE 息屏指纹解锁 aod 5g都有问题 这些你都解决了？？厉害呀我的哥

**Comment by SaKongA** [comment]
https://github.com/xjl12/android_device_xiaomi_atom/commit/960895bc5ba83c040d4bac330c4ac7dcc817b3b8

是这个commit修复的VoLTE吗

**Comment by xjl12** [comment]
Yes, It 's a part. It's only reenable VoLTE when the phone first boot. And there are other libraries added into system also make an effect.

**Comment by SaKongA** [comment]
Is this just a part? What changes do I need to make else? Ask for advice!

**Comment by xjl12** [comment]
https://github.com/xjl12/android_device_xiaomi_atom/tree/PixelExperience-Plus/ims
This directory is the main part. And all this binary files are copied from MIUI except the libsink library because of the compatibility. But libsink is a part of Video Call, if you don't mind it, it can be ignored.

**Comment by SaKongA** [comment]
OK, I see.Thank you very much. Is your AOD normal now？

**Comment by xjl12** [comment]
https://github.com/xjl12/android_device_xiaomi_atom/commit/1aaaa9e1ae41589e516951ee11943fdb1c6aba88
This is for AOD. Everything with fingerprint is OK now, including FOD, AOD, Fingerprint Pay.

**Comment by ZhcnPanda** [comment]
我对设备树不太会 你能帮我修一下K30U的息屏指纹和VoLTE吗 感谢！
