### ISSUE TITLE
关于新安装的应用无法连接到网络的问题

### ISSUE THREAD

**Issue by KADGang** [xjl12/android_device_xiaomi_atom#9]
刷完这个rom后出现了一些新安装的应用无法连接到网络的问题，目前测试出的有腾讯QQ，bilibili国际版，project sekai这些app，但是这些网络问题均可以重启解决。但是重启之后又有新安装的应用就有可能出现同样的问题，而且自适应主题色也不起作用了。不管怎么说还是谢谢大佬。

**Comment by xjl12** [comment]
考虑到该问题偶然性很强，第一，你新安装的软件不是每一个都不能联网，第二，重启能够解决；并且我也没有遇到过这种情况，无法诊断，抱歉。

建议：
1、核对一下底包版本`adb shell getprop ro.vendor.build.version.incremental`输出是否为22.1.19
2、谷歌版未经充分测试，建议使用纯净版
3、主题色适配的确偶尔失灵，但涉及谷歌私有代码，目前无法修复。

**Comment by KADGang** [comment]
好的，谢谢大佬
